version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              libelf-dev libdw-dev binutils-dev \
              autoconf automake libtool pkg-config autoconf-archive \
              g++ default-jre-headless \
              make git gdb wget \
              libboost-iostreams-dev libboost-regex-dev \
              libboost-serialization-dev libboost-filesystem-dev
      - checkout
      - run:
          name: Update submodules
          command: git submodule update --init --recursive
      - run:
          name: Build submodules
          command: make -C contrib -j 2
      - run:
          name: Build project
          command: |
            . contrib/env.sh
            ./autogen.sh
            ./configure
            make -j 2
      - persist_to_workspace:
          root: /root
          paths: project
  test:
    requires:
      - build
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y ca-certificates make build-essential g++ autoconf automake libtool \
              libelf-dev python3 git libunwind-dev \
              libboost-iostreams-dev libboost-regex-dev \
              libboost-serialization-dev libboost-filesystem-dev
      - attach_workspace:
          at: /root
      - run:
          name: Run tests
          command: make -C /root/project/tests -j 2

workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires:
            - build
